/**
 * Deterministic graph generator for TSP problem instances.
 *
 * ## How it works
 *
 * `generateGraph()` builds a complete TSP graph from a seed, node count, and
 * configuration. The process is entirely deterministic — the same seed and
 * options always produce identical node positions and edge weights. This is
 * the foundation that enables reproducible benchmarking and shareable
 * problem instances.
 *
 * ## Weight modes
 *
 * Two strategies control how edge weights are assigned:
 *
 * - **`random`**: Weights are drawn uniformly from `[wmin, wmax]` using the
 *   seeded RNG. Fast and suitable for stress-testing algorithms with arbitrary
 *   weight matrices. No relationship between geometric positions and weights.
 *
 * - **`euclidean`**: Weights are derived from the 2D Euclidean distance
 *   between node positions, linearly mapped to the `[wmin, wmax]` range.
 *   This makes the graph visually meaningful — nearby nodes have lower
 *   edge costs, which improves the intuition of the animated visualization.
 *   The mapping uses the min/max pairwise distances across all node pairs
 *   so weight distribution scales naturally with the layout.
 *
 * ## Symmetric vs asymmetric
 *
 * - **Symmetric**: `weight[i→j] == weight[j→i]`. The matrix is filled by
 *   iterating only over `i < j` and writing both entries — halving RNG calls
 *   and guaranteeing symmetry.
 *
 * - **Asymmetric**: Each directed edge `i→j` (for `i != j`) gets its own
 *   weight. In euclidean mode, a small random jitter is added to break
 *   symmetry (avg 5% of the weight range), producing realistic asymmetric
 *   travel costs while keeping the euclidean baseline visible.
 *
 * ## Coordinate system
 *
 * Node positions are independent uniform draws in the [0,1] unit square,
 * generated by the first 2n RNG calls. All subsequent RNG calls feed the
 * weight assignment logic.
 */

import { createRng } from '@/lib/rng';
import { makeGraph, type Graph } from './types';

/**
 * Weight generation strategy.
 *
 * - `random`: Edge weights are uniform random values in [wmin, wmax], with no
 *   relationship to node positions.
 * - `euclidean`: Edge weights are derived from the Euclidean distance between
 *   nodes, linearly interpolated into [wmin, wmax]. Gives visual coherence to
 *   the 2D/3D layout.
 */
export type WeightMode = 'random' | 'euclidean';

/**
 * Configuration for generating a single TSP graph instance.
 *
 * Every generated graph is fully determined by `seed` combined with `n`,
 * `type`, `weightRange`, and `weightMode`. Providing `rng` (e.g., from a
 * parent generator) overrides the internal seed-based RNG — useful for
 * chaining or reproducible batch generation.
 */
export interface GenerateOptions {
  /** Number of nodes (cities) in the graph. */
  readonly n: number;
  /** Whether edge weights are symmetric or asymmetric. */
  readonly type: 'symmetric' | 'asymmetric';
  /** Inclusive [min, max] range for edge weights. */
  readonly weightRange: readonly [number, number];
  /** 32-bit seed that fully determines the generated instance. */
  readonly seed: number;
  /** Weight generation strategy. Defaults to 'random' if omitted. */
  readonly weightMode?: WeightMode;
  /** Optional pre-seeded RNG, overrides the internal seed when provided. */
  readonly rng?: () => number;
}

/**
 * Pre-computed bounds for the euclidean-to-weight interpolation.
 *
 * `minDist`/`maxDist` are the minimum and maximum Euclidean distances across
 * all node pairs. `wmin`/`wmax` are the target weight range. Together they
 * define the linear interpolation from distance-space to weight-space.
 */
interface EuclideanRange {
  /** Shortest pairwise Euclidean distance among all node pairs. */
  readonly minDist: number;
  /** Longest pairwise Euclidean distance among all node pairs. */
  readonly maxDist: number;
  /** Minimum weight in the target range (inclusive). */
  readonly wmin: number;
  /** Maximum weight in the target range (inclusive). */
  readonly wmax: number;
}

/**
 * Maps the Euclidean distance between two nodes to a weight in [wmin, wmax].
 *
 * Uses linear interpolation: `d → wmin + t*(wmax-wmin)` where `t` is the
 * normalized position of `d` within `[minDist, maxDist]`. The result is
 * rounded to an integer because TSP weights are easier to reason about as
 * discrete values. When `maxDist <= minDist` (e.g., single-node graphs or
 * all nodes at identical positions), falls back to `wmin`.
 *
 * @param a - First node with x/y position.
 * @param b - Second node with x/y position.
 * @param range - Pre-computed distance bounds and target weight range.
 * @returns Integer weight in [wmin, wmax].
 */
function euclideanWeight(a: { x: number; y: number }, b: { x: number; y: number }, range: EuclideanRange): number {
  if (range.maxDist <= range.minDist) return Math.round(range.wmin);
  const d = Math.sqrt((a.x - b.x) ** 2 + (a.y - b.y) ** 2);
  const t = (d - range.minDist) / (range.maxDist - range.minDist);
  return Math.round(range.wmin + t * (range.wmax - range.wmin));
}

/**
 * Finds the minimum and maximum Euclidean distances across all node pairs.
 *
 * Used by the euclidean weight mode to compute the interpolation range so
 * that weights scale naturally with the actual node layout. Skips self-pairs
 * (i == i). Returns `{ minDist: 0, maxDist: 0 }` for edge cases where no
 * valid pairs exist.
 *
 * @param nodes - Array of nodes with x/y positions.
 * @returns Bounds object with minDist and maxDist.
 */
function distanceBounds(
  nodes: ReadonlyArray<{ x: number; y: number }>,
): { minDist: number; maxDist: number } {
  let minDist = Number.POSITIVE_INFINITY;
  let maxDist = 0;
  for (let i = 0; i < nodes.length; i++) {
    for (let j = i + 1; j < nodes.length; j++) {
      const a = nodes[i];
      const b = nodes[j];
      if (a === undefined || b === undefined) continue;
      const d = Math.sqrt((a.x - b.x) ** 2 + (a.y - b.y) ** 2);
      if (d < minDist) minDist = d;
      if (d > maxDist) maxDist = d;
    }
  }
  if (minDist === Number.POSITIVE_INFINITY) return { minDist: 0, maxDist: 0 };
  return { minDist, maxDist };
}

/**
 * Fills the upper triangle of the weight matrix and mirrors to the lower
 * triangle, enforcing strict symmetry (`weight[i→j] == weight[j→i]`).
 *
 * Only iterates over `i < j`, calling `pick` once per unordered pair. This
 * halves the number of RNG calls compared to filling the full matrix, and
 * guarantees perfect symmetry without any post-hoc correction.
 *
 * @param weights - Mutable Float32Array (n×n) to fill.
 * @param n - Number of nodes.
 * @param pick - Callback returning the weight for pair (i, j), i < j.
 */
function fillSymmetric(
  weights: Float32Array,
  n: number,
  pick: (i: number, j: number) => number,
): void {
  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      const w = pick(i, j);
      weights[i * n + j] = w;
      weights[j * n + i] = w;
    }
  }
}

/**
 * Fills the entire weight matrix for an asymmetric graph, skipping only the
 * diagonal (self-loops). Each directed edge `i→j` (i != j) gets its own
 * weight via `pick(i, j)`. In euclidean mode, `pick` adds jitter to break
 * symmetry; in random mode, every pair gets an independent uniform draw.
 *
 * @param weights - Mutable Float32Array (n×n) to fill.
 * @param n - Number of nodes.
 * @param pick - Callback returning the weight for directed edge i→j.
 */
function fillAsymmetric(
  weights: Float32Array,
  n: number,
  pick: (i: number, j: number) => number,
): void {
  for (let i = 0; i < n; i++) {
    for (let j = 0; j < n; j++) {
      if (i === j) continue;
      weights[i * n + j] = pick(i, j);
    }
  }
}

/**
 * Generates a complete, deterministic TSP graph instance.
 *
 * ## Process
 *
 * 1. Seeds the RNG and generates `n` node positions in [0,1]^2.
 * 2. Allocates an n×n Float32Array for the weight matrix (diagonal = 0).
 * 3. Based on `weightMode` and `type`, fills the matrix:
 *    - `euclidean` + `symmetric`: distance-derived weights, mirrored.
 *    - `euclidean` + `asymmetric`: distance-derived weights with per-edge jitter.
 *    - `random` + `symmetric`: independent uniform weights, mirrored.
 *    - `random` + `asymmetric`: independent uniform weights, full matrix.
 * 4. Returns an immutable Graph via `makeGraph()`.
 *
 * The same (opts) always produces bit-identical output.
 *
 * @param opts - Generation configuration (n, seed, weight mode, etc.).
 * @returns A new, immutable Graph instance.
 */
export function generateGraph(opts: GenerateOptions): Graph {
  const { n, type, weightRange, seed } = opts;
  const rng = opts.rng ?? createRng(seed);
  const [wmin, wmax] = weightRange;
  const mode: WeightMode = opts.weightMode ?? 'random';
  const nodes = Array.from({ length: n }, (_, i) => ({
    id: i,
    x: rng(),
    y: rng(),
  }));
  const weights = new Float32Array(n * n);
  for (let i = 0; i < n; i++) weights[i * n + i] = 0;

  if (mode === 'euclidean') {
    const bounds = distanceBounds(nodes);
    const range: EuclideanRange = { ...bounds, wmin, wmax };
    const pick = (i: number, j: number): number => {
      const a = nodes[i];
      const b = nodes[j];
      if (a === undefined || b === undefined) return wmin;
      const w = euclideanWeight(a, b, range);
      if (type === 'asymmetric' && i !== j) {
        const jitter = Math.round((rng() - 0.5) * Math.max(1, (wmax - wmin) * 0.05));
        return Math.max(1, w + jitter);
      }
      return w;
    };
    if (type === 'symmetric') fillSymmetric(weights, n, pick);
    else fillAsymmetric(weights, n, pick);
  } else if (type === 'symmetric') {
    fillSymmetric(weights, n, () => Math.round(wmin + rng() * (wmax - wmin)));
  } else {
    fillAsymmetric(weights, n, () => Math.round(wmin + rng() * (wmax - wmin)));
  }

  return makeGraph(nodes, weights, type);
}
